type User @table {
  username: String!
  email: String
  createdAt: Timestamp!
}

type Note @table {
  user: User!
  title: String!
  content: String!
  isImportant: Boolean
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type Category @table {
  user: User!
  name: String!
  createdAt: Timestamp!
}

type NoteCategory @table(key: ["note", "category"]) {
  note: Note!
  category: Category!
  createdAt: Timestamp!
}